# Generated by Django 4.2.1 on 2023-06-16 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0003_alter_missingperson_date_of_disappearance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpGender', models.CharField(max_length=1)),
                ('gender_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
