# Generated by Django 4.2.1 on 2023-06-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0004_gender_alter_missingperson_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpRace', models.CharField(max_length=50)),
            ],
        ),
    ]
