# Generated by Django 4.2.1 on 2023-06-16 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0005_race'),
    ]

    operations = [
        migrations.AlterField(
        model_name='missingperson',
        name='race',
        field=models.CharField(max_length=20),
),
    ]
