# Generated by Django 4.2.1 on 2023-06-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0006_alter_missingperson_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
