# Generated by Django 4.2.1 on 2023-06-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0007_uploadpicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadPicture',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
