# Generated by Django 4.2.1 on 2023-06-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0009_alter_missingperson_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
