# Generated by Django 4.2.1 on 2023-06-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0010_alter_missingperson_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='picture',
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
