# Generated by Django 4.2.1 on 2023-06-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0011_profile_remove_missingperson_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='race',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
