# Generated by Django 4.2.1 on 2023-06-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0012_delete_gender_alter_missingperson_race_delete_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='date_of_disappearance',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
