# Generated by Django 4.2.1 on 2023-06-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0013_alter_missingperson_date_of_disappearance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
