# Generated by Django 4.2.1 on 2023-06-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMP', '0014_delete_profile_missingperson_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='age_at_missing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='city_of_disappearance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='date_of_disappearance',
            field=models.DateField(blank=True, default='1999-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='state_of_disappearance',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
